image: electronuserland/builder

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - cd analysis-lib
  - npm install
  - mkdir db
  - sqlite3 db/analysis-lib.db < ./src/db-scripts/tables/reset-tables.sql
  - cd ..
  - cd electron-app
  - npm install
  - cd ..

build:windows:
  script:
    - apt-get install -y apt-utils zip python2.7 python2.7-dev wine1.8 wine32 mono-devel
    - cd electron-app
    - npm run build:windows-dir

build:mac:
  script:
    - cd electron-app
    - npm run build:mac-dir

build:linux:
  script:
    - cd electron-app
    - npm run build:linux-dir
