image: electronuserland/builder

before_script:
  - apt-get update -qq
  - apt-get install -y -qq sqlite3 libsqlite3-dev
  - export NVM_DIR="$PWD/.nvm" && (git clone https://github.com/creationix/nvm.git "$NVM_DIR"; cd "$NVM_DIR"; git pull; git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`) && \. "$NVM_DIR/nvm.sh"
  - nvm install --lts --latest-npm
  - npm config --global set cache "$PWD/.npm"
  - cd analysis-lib
  - npm install
  - mkdir db
  - sqlite3 db/analysis-lib.db < ./src/db-scripts/tables/reset-tables.sql
  - cd ..
  - cd electron-app
  - npm install

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
  - analysis-lib/node_modules/
  - electron-app/node_modules/
  - .nvm/
  - .npm/

build:windows:
  image: electronuserland/builder:wine
  script:
    - npm run build:windows
  artifacts:
    paths:
    - electron-app/build/Musical Turk Setup *.exe
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines

build:mac:
  script:
    - npm run build:mac
  artifacts:
    paths:
    - electron-app/build/Musical Turk-*-mac.zip
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines

build:linux:
  script:
    - npm run build:linux
  artifacts:
    paths:
    - electron-app/build/musical-turk.tar.gz
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines

