before_script:
  - apt-get update -qq
  - apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - cd analysis-lib
  - npm install
  - mkdir db
  - sqlite3 db/analysis-lib.db < ./src/db-scripts/tables/reset-tables.sql
  - cd ..
  - cd electron-app
  - npm install
  - cd ..

#only:
#    refs:
#      - master

build:windows:
  image: electronuserland/builder:wine
  script:
    - cd electron-app
    - npm run build:windows
  artifacts:
    paths:
    - electron-app/build/Musical Turk Setup 1.0.0.exe
    expire_in: 1 week

build:mac:
  image: electronuserland/builder
  script:
    - cd electron-app
    - npm run build:mac
  artifacts:
    paths:
    - electron-app/build/Musical Turk-1.0.0-mac.tar.gz
    expire_in: 1 week

build:linux:
  image: electronuserland/builder
  script:
    - cd electron-app
    - npm run build:linux
  artifacts:
    paths:
    - electron-app/build/musical-turk.tar.gz
    expire_in: 1 week
