image: electronuserland/builder

before_script:
  - apt-get update -qq
  - apt-get install -y -qq sqlite3 libsqlite3-dev curl
  - apt-get -y autoclean
  - curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source $NVM_DIR/nvm.sh
  - nvm install --lts --latest-npm
  - cd analysis-lib
  - npm install
  - mkdir db
  - sqlite3 db/analysis-lib.db < ./src/db-scripts/tables/reset-tables.sql
  - cd ..
  - cd electron-app
  - npm install

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

build:windows:
  image: electronuserland/builder:wine
  script:
    - npm run build:windows
  artifacts:
    paths:
    - electron-app/build/Musical Turk Setup *.exe
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines

build:mac:
  script:
    - npm run build:mac
  artifacts:
    paths:
    - electron-app/build/Musical Turk-*-mac.zip
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines

build:linux:
  script:
    - npm run build:linux
  artifacts:
    paths:
    - electron-app/build/musical-turk.tar.gz
    expire_in: 1 week
  only:
    refs:
      - master
      - 291-fix-gitlab-pipelines
